### ISSUE TITLE
Create a backend for Product Listing

### ISSUE THREAD

**Issue by Wajid2001** [Wajid2001/Iha-ecommerce#2]
### Task 1
- [ ]  Create a item model in .\backend app ,i.e, .\backend\models.py

Item model must contain the following things in it 

- [ ] 1. Name of item
- [ ] 2. Price
- [ ] 3. Primary key to User model, it should be Many item to one User.
- [ ] 4. a_del Admin delete boolean, so that if the admin of the web app want to partially remove the item, it must use this option

### Task 2
- [ ]  After Above, Create the api for Item CRUD operation, in .\backend\views.py and .\backend\urls.py

###  Finalizing them
After all above tasks are done then create a pull request or if possible merge changes into main branch.

**Comment by Wajid2001** [comment]
Hi @jahnaviii0518 , 
What is your progress status?
